import { useLocation, useNavigate } from "react-router-dom";
import Sidebar from "../../components/student/Sidebar";
import "./InterviewResult.css";

export default function InterviewResult() {
  const location = useLocation();
  const navigate = useNavigate();

  const state = location.state;

  if (!state) {
    return (
      <div className="result-page">
        <h2>No interview result found.</h2>

        <button
          className="back-btn"
          onClick={() => navigate("/mock-interview")}
        >
          Back to Interview
        </button>
      </div>
    );
  }

  return (
    <div className="layout">
      <Sidebar />

      <div className="result-main">
        <h1>🎉 Interview Evaluation</h1>

        {/* Overall Score */}

        <div className="score-card">
          <h2>Overall Score</h2>

          <div className="score">
            {state.overallScore ?? 0}/100
          </div>
        </div>

        {/* Interview Summary */}

        <div className="summary-card">
          <h3>📋 Interview Summary</h3>

          <div className="summary-grid">
            <div>
              <strong>Role</strong>
              <p>{state.role || "-"}</p>
            </div>

            <div>
              <strong>Questions Answered</strong>
              <p>
                {state.completedQuestions ?? "-"} / {state.totalQuestions ?? "-"}
              </p>
            </div>

            <div>
              <strong>Duration</strong>
              <p>{state.duration || "-"}</p>
            </div>

            <div>
              <strong>Date</strong>
              <p>{state.interviewDate || "-"}</p>
            </div>

            <div>
              <strong>Generated By</strong>
              <p>{state.generatedBy || "Gemini AI"}</p>
            </div>
          </div>
        </div>

        {/* Scores */}

        <div className="stats">
          <div className="stat-card">
            <h3>Technical Knowledge</h3>
            <p>{state.technicalKnowledge ?? 0}/10</p>
          </div>

          <div className="stat-card">
            <h3>Communication</h3>
            <p>{state.communication ?? 0}/10</p>
          </div>

          <div className="stat-card">
            <h3>Confidence</h3>
            <p>{state.confidence ?? 0}/10</p>
          </div>
        </div>

        {/* Feedback */}

        <div className="feedback-section">
          <div className="feedback-card">
            <h3>✅ Strengths</h3>

            <ul>
              {(state.strengths || []).map((item, index) => (
                <li key={index}>{item}</li>
              ))}
            </ul>
          </div>

          <div className="feedback-card">
            <h3>📈 Areas to Improve</h3>

            <ul>
              {(state.improvements || []).map((item, index) => (
                <li key={index}>{item}</li>
              ))}
            </ul>
          </div>
        </div>

        {/* AI Feedback */}

        <div className="final-feedback">
          <h3>🤖 AI Feedback</h3>

          <p>{state.feedback}</p>
        </div>

        <button
          className="back-btn"
          onClick={() => navigate("/mock-interview")}
        >
          Take Another Interview
        </button>
      </div>
    </div>
  );
}